{% set name = "austin" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/P403n1x87/austin/archive/v{{ version }}.tar.gz
  sha256: b9cad3670c5f6f750d2c8dc6869a7c5b45fe42305185a0cd3f249e1aa017a7ea

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - automake  # [not win]
    - autoconf  # [not win]
    - make  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
    - autotools_clang_conda  # [win]
    - binutils  # [linux]
    - libunwind  # [linux]
  host:
    - python
  run:
    - python

test:
  commands:
    - austin --help
    - austinp --help

about:
  home: https://github.com/P403n1x87/austin
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: A Frame Stack Sampler for CPython

  description: |
    Austin is a Python frame stack sampler for CPython written in pure C. Samples are collected
    by reading the CPython interpreter virtual memory space in order to retrieve information about
    the currently running threads along with the stack of the frames that are being executed. Hence,
    one can use Austin to easily make powerful statistical profilers that have minimal impact on the
    target application and that don't require any instrumentation.
  dev_url: https://github.com/P403n1x87/austin

extra:
  recipe-maintainers:
    - synapticarbors
