{% set name = "austin" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/P403n1x87/austin/archive/v{{ version }}.tar.gz
  sha256: adc7ce66478142ae0e0922c8ad2031dbf908c6d9fa2c3f6e9793888bd11e67ab

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - automake  # [not win]
    - autoconf  # [not win]
    - make  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
    - autotools_clang_conda  # [win]
  host:
    - python
  run:
    - python

test:
  commands:
    - austin --help

about:
  home: https://github.com/P403n1x87/austin
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: A Frame Stack Sampler for CPython

  description: |
    Austin is a Python frame stack sampler for CPython written in pure C. Samples are collected 
    by reading the CPython interpreter virtual memory space in order to retrieve information about 
    the currently running threads along with the stack of the frames that are being executed. Hence, 
    one can use Austin to easily make powerful statistical profilers that have minimal impact on the 
    target application and that don't require any instrumentation.
  dev_url: https://github.com/P403n1x87/austin

extra:
  recipe-maintainers:
    - synapticarbors
